// Generated by scripts/gen-types.sh (Supabase MCP generate_typescript_types).
// Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      appointments: {
        Row: {
          appt_date: string;
          appt_time: string | null;
          appt_type: string | null;
          created_at: string | null;
          duration_minutes: number | null;
          id: string;
          location_id: string | null;
          notes: string | null;
          patient_id: string | null;
          provider_id: string | null;
          status: string | null;
          updated_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["appointments"]["Row"]> & {
          appt_date: string;
        };
        Update: Partial<Database["public"]["Tables"]["appointments"]["Row"]>;
        Relationships: [];
      };
      billing_events: {
        Row: {
          amount: number | null;
          claim_id: string | null;
          created_at: string | null;
          description: string | null;
          event_date: string | null;
          event_type: string | null;
          id: string;
          patient_id: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["billing_events"]["Row"]>;
        Update: Partial<Database["public"]["Tables"]["billing_events"]["Row"]>;
        Relationships: [];
      };
      blog_posts: {
        Row: {
          coming_soon: boolean | null;
          content: Json | null;
          content_html: string | null;
          created_at: string | null;
          episode: number | null;
          excerpt: string | null;
          id: string;
          image: string | null;
          image_1x1: string | null;
          image_3x4: string | null;
          image_alt: string | null;
          image_prompts: Json | null;
          published_date: string | null;
          read_time: string | null;
          related_service: string | null;
          release_date: string | null;
          series_title: string | null;
          slug: string;
          tag: string | null;
          title: string;
          updated_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["blog_posts"]["Row"]> & {
          slug: string;
          title: string;
        };
        Update: Partial<Database["public"]["Tables"]["blog_posts"]["Row"]>;
        Relationships: [];
      };
      booking_requests: {
        Row: {
          appt_type: string | null;
          created_at: string | null;
          email: string | null;
          id: string;
          insurance: string | null;
          ip: unknown;
          location_id: string | null;
          name: string;
          notes: string | null;
          phone: string | null;
          preferred_date: string | null;
          preferred_time: string | null;
          status: string | null;
          user_agent: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["booking_requests"]["Row"]> & {
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["booking_requests"]["Row"]>;
        Relationships: [];
      };
      conditions: {
        Row: {
          created_at: string | null;
          hero_image: string | null;
          id: string;
          overview: string | null;
          reassurance: string | null;
          recovery: string | null;
          related_service: string | null;
          seo_text: string | null;
          slug: string;
          sort_order: number | null;
          symptoms: string[] | null;
          tagline: string | null;
          title: string;
          treatments: string[] | null;
          updated_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["conditions"]["Row"]> & {
          slug: string;
          title: string;
        };
        Update: Partial<Database["public"]["Tables"]["conditions"]["Row"]>;
        Relationships: [];
      };
      google_reviews: {
        Row: {
          author_name: string | null;
          id: string;
          location: string | null;
          rating: number | null;
          review_date: string | null;
          text: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["google_reviews"]["Row"]>;
        Update: Partial<Database["public"]["Tables"]["google_reviews"]["Row"]>;
        Relationships: [];
      };
      locations: {
        Row: {
          address: string | null;
          display: string | null;
          id: string;
          label: string | null;
          lat: number | null;
          lng: number | null;
          maps_url: string | null;
          query: string | null;
          sort_order: number | null;
        };
        Insert: Partial<Database["public"]["Tables"]["locations"]["Row"]> & {
          id: string;
        };
        Update: Partial<Database["public"]["Tables"]["locations"]["Row"]>;
        Relationships: [];
      };
      medical_codes: {
        Row: { code: string; code_type: string | null; description: string };
        Insert: { code: string; code_type?: string | null; description: string };
        Update: Partial<{ code: string; code_type: string | null; description: string }>;
        Relationships: [];
      };
      patient_invoices: {
        Row: {
          claim_id: string | null;
          copay: number | null;
          created_at: string | null;
          deductible_applied: number | null;
          description: string | null;
          id: string;
          insurance_paid: number | null;
          invoice_date: string | null;
          patient_id: string | null;
          patient_owes: number | null;
          status: string | null;
          total_charged: number | null;
        };
        Insert: Partial<Database["public"]["Tables"]["patient_invoices"]["Row"]> & {
          id: string;
        };
        Update: Partial<Database["public"]["Tables"]["patient_invoices"]["Row"]>;
        Relationships: [];
      };
      patient_visits: {
        Row: {
          codes: string[] | null;
          created_at: string | null;
          id: string;
          notes: string | null;
          patient_id: string | null;
          visit_date: string;
          visit_type: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["patient_visits"]["Row"]> & {
          visit_date: string;
        };
        Update: Partial<Database["public"]["Tables"]["patient_visits"]["Row"]>;
        Relationships: [];
      };
      patients: {
        Row: {
          address: string | null;
          age: number | null;
          allergies: string[] | null;
          aob_date: string | null;
          aob_signed: boolean | null;
          blood_type: string | null;
          bmi: number | null;
          condition: string | null;
          copay_amount: number | null;
          created_at: string | null;
          deductible: number | null;
          dob: string | null;
          email: string | null;
          emergency_contact: string | null;
          emergency_phone: string | null;
          financial_date: string | null;
          financial_signed: boolean | null;
          group_number: string | null;
          hipaa_date: string | null;
          hipaa_signed: boolean | null;
          id: string;
          implanted_devices: string[] | null;
          insurance: string | null;
          intro_message: string | null;
          last_visit: string | null;
          medications: string[] | null;
          member_id: string | null;
          name: string;
          next_appt: string | null;
          phone: string | null;
          primary_language: string | null;
          prior_auth: string | null;
          prior_auth_expiration: string | null;
          provider: string | null;
          referred_by: string | null;
          roi_date: string | null;
          roi_signed: boolean | null;
          sex: string | null;
          signed_up_date: string | null;
          smoking_status: string | null;
          status: string | null;
          subscriber_dob: string | null;
          subscriber_name: string | null;
          subscriber_relationship: string | null;
          surgical_consent_date: string | null;
          surgical_consent_signed: boolean | null;
          updated_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["patients"]["Row"]> & {
          id: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["patients"]["Row"]>;
        Relationships: [];
      };
      providers: {
        Row: {
          bio: string | null;
          certifications: string[] | null;
          created_at: string | null;
          education: string[] | null;
          email: string | null;
          id: string;
          initials: string | null;
          languages: string[] | null;
          location: string | null;
          name: string;
          phone: string | null;
          role: string | null;
          schedule: string | null;
          specialty: string | null;
          status: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["providers"]["Row"]> & {
          id: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["providers"]["Row"]>;
        Relationships: [];
      };
      services: {
        Row: {
          approach: string[] | null;
          benefits: string[] | null;
          conditions: string[] | null;
          created_at: string | null;
          description: string | null;
          detail: string | null;
          id: string;
          slug: string;
          sort_order: number | null;
          subtitle: string | null;
          title: string;
          updated_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["services"]["Row"]> & {
          slug: string;
          title: string;
        };
        Update: Partial<Database["public"]["Tables"]["services"]["Row"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<K extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][K]["Row"];
export type TablesInsert<K extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][K]["Insert"];
export type TablesUpdate<K extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][K]["Update"];
