import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("contact", "routes/contact.tsx"),
  route("reviews", "routes/reviews.tsx"),
  route("faq", "routes/faq.tsx"),
  route("blog", "routes/blog.tsx"),
  route("blog/:slug", "routes/blog-post.tsx"),
  route("book", "routes/book.tsx"),
  route("services/:slug", "routes/service.tsx"),
  route("conditions/:slug", "routes/condition.tsx"),
  route("doczoc", "routes/doczoc.tsx"),
  route("doczoc/signin", "routes/doczoc-signin.tsx"),
  route("doczoc/dashboard", "routes/doczoc-dashboard.tsx"),
  route("doczoc/patients", "routes/doczoc-patients.tsx"),
  route("doczoc/patients/:id", "routes/doczoc-patient.tsx"),
  route("doczoc/clients", "routes/doczoc-clients.tsx"),
  route("doczoc/calendar", "routes/doczoc-calendar.tsx"),
  route("doczoc/appearance", "routes/doczoc-appearance.tsx"),
  route("doczoc/billing", "routes/doczoc-billing.tsx"),
  route("doczoc/insights", "routes/doczoc-insights.tsx"),
  route("doczoc/provider", "routes/doczoc-provider.tsx"),
  route("doczoc/in-person", "routes/doczoc-in-person.tsx"),
  route("doczoc/apis", "routes/doczoc-apis.tsx"),
  route("doczoc/reports", "routes/doczoc-reports.tsx"),
  route("doczoc/rcm", "routes/doczoc-rcm.tsx"),
  route("dev", "routes/dev.tsx"),
  route("webgl", "routes/webgl.tsx"),
] satisfies RouteConfig;
